spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
        time-between-eviction-runs: 30000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.36.4.173:3306/sunshine?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: o@S$9i3r6V
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    xyz:
      lizhaorong: trace

server:
  servlet:
    context-path: /api